{% set name = "pe-configurator" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pe-configurator-{{ version }}.tar.gz
  sha256: 61e638c1c89a6a5b8687c94c98281dd442f88cccb2f2745ef92a75e95315bf9b

build:
  entry_points:
    - peconfigurator = peconfigurator.proc_samples:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.0
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >=3.6
    - asimov >=0.4.0
    - lalsuite >=7.14
    - pandas
    - pesummary >=1.0.2
    - nbformat
    - bilby
    - jupyter
    - nbconvert
test:
  imports:
    - peconfigurator
  commands:
    - pip check
    - peconfigurator --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pe-configurator/
  summary: Tools to identify waveform settings and prior bounds for gravitational wave parameter estimation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - transientlunatic
    - mj-will
